package org.team4u.test;

import com.alibaba.druid.pool.DruidDataSource;
import org.team4u.dao.core.Dao;
import org.team4u.dao.core.SimpleDao;
import org.team4u.sql.builder.Sql;
import org.team4u.sql.builder.content.FileSqlContentManager;
import org.team4u.sql.builder.content.SqlContentManager;
import org.team4u.sql.builder.content.SqlContents;

import javax.sql.DataSource;

/**
 * @author Jay Wu
 */
public class TestUtil {

    public static DataSource createDataSource() {
        DruidDataSource ds = new DruidDataSource();
        ds.setUrl("jdbc:hsqldb:mem:db");
        ds.setUsername("sa");
        ds.setPassword("");
        ds.setInitialSize(1);
        return ds;
    }

    public static SimpleDao createDao() {
        return new SimpleDao(createDataSource());
    }

    public static SimpleDao createAndInitDao() {
        SimpleDao dao = createDao();
        initTables(dao);
        return dao;
    }

    public static void initTables(Dao dao) {
        dao.execute(new Sql().setContent("CREATE TABLE client (\n" +
                "  client_id varchar(36) NOT NULL PRIMARY KEY,\n" +
                "  name varchar(150) DEFAULT NULL\n" +
                ");"));

        dao.execute(new Sql().setContent("CREATE TABLE token (\n" +
                "  id integer generated by default as identity(start with 1) not null primary key,\n" +
                "  name varchar(150) DEFAULT NULL\n" +
                ");"));
    }

    public static void initSqlContent() {
        SqlContentManager manager = new FileSqlContentManager("test.sql");
        SqlContents.getInstance().register(manager);
    }
}